---

- hosts: localhost
  tasks:

    - name: create a simple text file
      shell: touch result.txt

    - name: remove result.txt
      file:
        path: /home/faisal/git-test/result.txt
        state: absent
    
    - name: sleep for 5 seconds
      command: /bin/sleep 5


